version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mcgill-stock-postgres
    restart: always
    environment:
      POSTGRES_DB: stock_portfolio
      POSTGRES_USER: mcgill_user
      POSTGRES_PASSWORD: mcgill123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U mcgill_user -d stock_portfolio
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local